package com.example.aaa123;


import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;


public class myDBHelper extends SQLiteOpenHelper {
    public myDBHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE PRODUCT ( _id INTEGER PRIMARY KEY AUTOINCREMENT,brandName TEXT,goodsName TEXT,skinType INTEGER, skinType2 INTEGER, mois DOUBLE, oil DOUBLE);");

        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 나잇전용 온리 수분 워시팩', '0', '4', '20.55', '47.92');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 나잇전용 온리 수분 크림', '0', '4', '29.65', '49.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 나잇전용 충만 에센스', '0', '1', '19.46', '13.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 나잇전용 충만 워시팩', '0', '1', '21.77', '11.85');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 나잇전용 충만팩', '0', '1', '13.2', '14.86');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 데이전용 라이트 로션', '0', '3', '52.48', '32.19');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17데이 데이전용 수분많은 로션', '0', '4', '22.45', '51.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17케어 순한 로션', '7', '3', '62.81', '34.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17케어 순한 에멀젼', '7', '3', '48.15', '51.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17케어 순한 토너', '7', '3', '54.67', '49.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '17케어 순한 페이셜 오일', '7', '4', '30.48', '42.09');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 국화 브라이트닝팩', '0', '3', '42.12', '44.08');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 로즈 브라이트닝팩', '0', '2', '46.71', '20.94');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 로션', '7', '2', '37.15', '17.85');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 미스트', '7', '1', '31.17', '32.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 수분크림', '7', '3', '44.71', '46.76');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 슬리핑팩', '7', '1', '34.88', '10.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 아이크림', '7', '3', '35.12', '30.91');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 에멀젼', '7', '2', '52.97', '24.62');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 에센스', '7', '1', '21.09', '12.13');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 재생크림', '7', '1', '34.55', '21.39');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 리프레쉬 토너', '7', '2', '64.31', '29.19');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 비타민 브라이트닝팩', '0', '3', '66.61', '36.63');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 워터마이즈 브라이트닝팩', '0', '3', '39.43', '44.85');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 콜라겐 브라이트닝팩', '0', '3', '50.96', '53.61');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 티트리 브라이트닝팩', '0', '2', '43.07', '14.75');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '17 days', '27데이 포도씨오일 브라이트닝팩', '0', '2', '37.7', '13.59');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '닥터렐마 재생 수분크림', '6', '3', '38.15', '33.64');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '닥터렐마 재생 스킨 패드', '6', '3', '52.48', '51.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '닥터렐마 재생 스팟 크림', '6', '3', '43.15', '34.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '닥터렐마 재생 에멀젼 팩', '6', '3', '49.88', '36.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '닥터렐마 재생크림', '6', '3', '46.51', '47.92');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '디지버드 나잇크림', '0', '3', '39.57', '47.96');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '디지버드 세럼', '0', '1', '28.42', '21.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '디지버드 에센스', '0', '3', '47.8', '34.63');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '디지버드 크림', '0', '1', '25.16', '23.94');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '디지버드 토너', '0', '2', '63.76', '15.77');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 나이트 딥크림', '0', '1', '30.47', '23.85');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 나이트 로션', '0', '1', '25.61', '26.05');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 나이트 세럼', '0', '1', '25.93', '20.12');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 나이트 아이크림', '0', '1', '25.28', '27.34');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 나이트 에센스', '0', '1', '20.96', '29.29');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 나이트 토너', '0', '1', '34.37', '26.79');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 데이 라이트크림', '0', '1', '27.02', '26.07');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 데이 로션', '0', '1', '20.61', '25.04');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 데이 세럼', '0', '1', '22.18', '24.82');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 데이 토너', '0', '1', '27.11', '28.65');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '밀크 데이 토너패드', '0', '1', '29.76', '25.05');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '백미 화이트닝 재생크림', '6', '4', '32.8', '37.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '백미 화이트닝 토너', '6', '3', '61.25', '30.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '연꽃 리커버리 모이스쳐 미스트', '6', '3', '45.16', '53.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '연꽃 리커버리 모이스쳐 밤', '6', '4', '29.45', '34.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '연꽃 리커버리 모이스쳐 에센스', '6', '4', '34.51', '46.9');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '연꽃 리커버리 모이스쳐 토너', '6', '3', '54.15', '48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'flow of skin', '연꽃 리커버리 세럼', '6', '2', '53.44', '28.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 라이트 나잇크림', '0', '3', '50.87', '43.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 라이트 로션', '0', '3', '59.87', '46.09');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 라이트 수분크림', '0', '3', '37.36', '38.49');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 라이트 에멀젼크림', '0', '3', '46.39', '39.3');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 라이트 유분크림', '0', '3', '47.86', '46.63');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 라이트세럼', '0', '3', '46.11', '54.3');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 수분에센스', '0', '3', '47', '48.6');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'ICE CREAM', 'MERIN 쿨링 수분패드', '0', '3', '46.09', '34.81');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '가는동자 오직 수분만 슬리핑팩', '0', '4', '22.49', '58.12');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '가는동자 오직 수분만 에센스', '0', '4', '34.1', '51.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '가는동자 오직 수분만 크림', '0', '4', '19.43', '51.06');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '가는동자 오직 수분만 토너', '0', '4', '28.49', '53.12');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '개감수 오일', '7', '2', '58.62', '9.4');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '개감수 오일 인 미스트', '7', '2', '64.03', '21.28');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '개감수 오일 인 에센스', '7', '2', '53.48', '13.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '개감수 오일 인 팩', '7', '2', '44.8', '11.5');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '겹달맞이 수분맞는 로션', '6', '2', '60.78', '11.57');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '겹달맞이 수분맞는 밤', '6', '2', '65', '27.5');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '겹달맞이 수분맞는 세럼', '6', '2', '46.48', '16.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '겹달맞이 수분맞는 팩', '6', '2', '64.85', '9.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '별패랭이 브라이트닝 에멀젼', '0', '3', '56.79', '36.98');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '별패랭이 브라이트닝 토너', '0', '3', '54.98', '34.05');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '털동자 세라마이드 세럼', '0', '1', '23.48', '25.95');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '털동자 세라마이드 오일', '0', '1', '15.44', '27.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'my flowers', '털동자 세라마이드 크림', '0', '1', '17.66', '24.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 CTI 리커버리 스팟 젤', '5', '1', '21.55', '10.49');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 CTI 리커버리 스팟 패드', '5', '4', '34.55', '12.75');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 시칼파트 red line 밤', '5', '4', '21.44', '43.05');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 시칼파트 sos 크림', '5', '3', '37.88', '30.45');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 시칼파트 spot 젤', '5', '4', '29.48', '35.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 아드랑스 아쿠아 세럼', '5', '2', '51', '23.49');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 아드랑스 아쿠아 크림 인 젤', '5', '3', '47.15', '44.94');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 트릭세이 스펀지 에센스', '5', '2', '59.48', '27.19');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'red spot store', '레스토 트릭세이 스펀지 팩', '5', '2', '50.88', '22.17');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'sttendance', '파도 하이드레이션 로션', '7', '1', '17.48', '22.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'sttendance', '파도 하이드레이션 스팟 크림', '7', '1', '23.46', '18.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'sttendance', '파도 하이드레이션 에멀젼', '7', '1', '18.97', '11.83');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'sttendance', '파도 하이드레이션 에센스', '7', '1', '18.33', '21.94');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'sttendance', '파도 하이드레이션 토너', '7', '1', '21.13', '9.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 드래곤 노멀라이즈 페이셜 에센스', '0', '2', '52.46', '13.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 드래곤 라이트 페이셜 에센스', '0', '3', '39.81', '38.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 드래곤 울트라 페이셜 에센스', '0', '1', '19.22', '8.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 딜라이트 수분 밤', '0', '4', '15.68', '50');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 딜라이트 수분 밤 스틱', '0', '4', '17.45', '53.46');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 딜라이트 수분 밤 워시팩', '0', '4', '19.45', '52.79');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 딜라이트 수분 밤 인 에센스', '0', '4', '14.16', '50.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 산톨 오일링 스마트 크림', '7', '2', '43.88', '21.45');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'swingswing', '스윙 산톨 오일링 스마트 팩', '7', '3', '39.45', '38.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '리커버리 스팟 젤 에센스', '5', '2', '36.78', '21.57');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '리커버리 스팟 젤 크림', '5', '2', '40.1', '26.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 로션', '0', '2', '44.84', '17.53');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 밤', '0', '1', '23.79', '12.89');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 세럼', '0', '2', '40.79', '19.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 에멀젼', '0', '3', '37.15', '44.91');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 오일 미스트', '0', '1', '34.35', '14.77');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 크림', '0', '4', '15.64', '54.89');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드레이션 토너', '0', '3', '39.78', '46.08');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '백투베이비 하이드에이션 미스트', '0', '3', '38.49', '42.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '투베스 씨드오일 수분크림 fot 데이', '0', '2', '42.49', '15.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '투베스 씨드오일 오일밤', '0', '1', '22.45', '10.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '투베스 씨드오일 워시팩 for 나이트', '0', '3', '64.15', '40.77');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '투비스 씨드오일 에센스 인 팩', '0', '1', '25.45', '8.74');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, 'to baby', '투비스 씨드오일 토너 for 모닝', '0', '1', '31.22', '9');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '나트레', '실론티 밸런싱 로션', '7', '2', '47.15', '27.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '나트레', '실론티 밸런싱 세럼', '7', '2', '57.5', '21.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '나트레', '실론티 밸런싱 스킨', '7', '3', '48.4', '30.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '나트레', '제주 한라봉 로션', '5', '2', '42.58', '25.46');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '나트레', '제주 한라봉 스킨', '5', '3', '49.45', '31.44');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '나트레', '제주 한라봉 크림', '5', '3', '35', '33.97');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '국화꽃 울트라 스킨 세럼', '7', '4', '30.44', '50.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '국화꽃 울트라 에센스 크림', '7', '1', '27.61', '27.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '국화꽃 울트라 에센스 패드', '7', '3', '41.87', '48.11');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '국화꽃 울트라 페이셜 에센스', '7', '4', '30.48', '52.49');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '국화꽃 울트라 페이셜 오일', '7', '1', '21.63', '17.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 로션', '0', '3', '43.84', '50.13');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 로션 for 1', '0', '1', '27.55', '18.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 오일밤', '0', '1', '20.87', '16.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 익스트림 크림', '0', '1', '20.48', '20.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 크림', '0', '3', '48.6', '31.58');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 크림 for 7', '7', '2', '46.4', '17.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '데이지', '데이지 플로럴 수분 패드', '0', '2', '40.8', '21.9');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '더테라피 리페어링 로션', '6', '3', '39.48', '33.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '더테라피 리페어링 밤', '6', '4', '19.45', '35.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '더테라피 리페어링 스팟 젤', '6', '3', '35.18', '45.19');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '더테라피 수분 에멀젼', '6', '2', '61.84', '23.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '더테라피 에센셜 미스트', '6', '4', '33.1', '48.72');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '센시 무첨가 스킨패드', '7', '2', '38.4', '10.9');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '비터', '센시 무첨가 저스트 수분밤', '7', '4', '20.49', '35.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 비타민D 수분 오일밤', '0', '4', '31.55', '46.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 비타민D 수분 크림', '0', '4', '29.15', '44.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 비타민D 수분 패드', '0', '4', '26.45', '42.79');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 오이 쿨링 롤러스킨', '5', '3', '49.75', '55');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 오이 쿨링 수분밤', '5', '2', '63.55', '27.86');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 오이 쿨링 슈퍼 크림', '5', '3', '47.18', '54.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 오이 쿨링 에센셜 팩', '5', '3', '45.11', '52.49');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 젤리 콜라겐 수분크림', '0', '1', '34.12', '22.76');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 젤리 콜라겐 에멀젼', '0', '1', '33.45', '24.09');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '산아이드', '아이드 젤리 콜라겐 에센스', '0', '2', '53.39', '25.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '로맨스 필링 세럼', '0', '3', '55.76', '49.46');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '로맨스 필링 에멀젼', '0', '4', '34.12', '40.55');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '로맨스 필링 토너', '0', '3', '57.26', '47.09');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '블루오션 콜라겐 세럼', '0', '3', '51.56', '53.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '블루오션 콜라겐 에멀젼', '0', '3', '53.11', '51.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '블루오션 콜라겐 토너', '0', '2', '50.67', '28.94');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '수분톡톡 치아씨드 미스트', '5', '1', '23.75', '26.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '수분톡톡 치아씨드 세럼', '5', '1', '22.45', '28.19');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '수분톡톡 치아씨드 에멀젼', '5', '1', '22.81', '29.76');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '세라', '수분톡톡 치아씨드 토너', '5', '1', '23.48', '27.06');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '스프타이프', '울트라 수분 베이스 토너', '5', '3', '59.48', '45.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 수선화 수분폭탄 결회복크림', '0', '4', '28.12', '48.04');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 수선화 수분폭탄 나잇전용세럼', '0', '4', '32.73', '34.11');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 수선화 수분폭탄 나잇크림', '0', '4', '31.41', '33.47');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 수선화 수분폭탄 필링패드', '0', '4', '32.89', '33.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 수선화 수분폭탄크림', '0', '4', '31.95', '33.97');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 나잇전용세럼', '0', '3', '30', '44.5');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 농축에센스', '0', '3', '33.07', '30.54');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 세럼', '0', '3', '26.33', '48.66');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 수분크림', '0', '3', '29.95', '54.97');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 수분패드', '0', '3', '60.27', '53.11');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 슬리핑팩', '0', '3', '30.34', '34.57');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 에센스', '0', '3', '24.55', '43');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '예쁜', '예쁜 울릉국화 유수분크림', '0', '3', '34.42', '32.57');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '느타리 슈퍼 모이스쳐 세럼', '5', '4', '33.45', '48.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '느타리 슈퍼 모이스쳐 오일', '5', '4', '27.45', '36.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '느타리 슈퍼 모이스쳐 크림 인 팩', '5', '4', '21.55', '40.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '울트라 수분 오일', '5', '2', '52.88', '26.85');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '울트라 수분 패드', '5', '2', '61.34', '24.92');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '피치씨드 하이드레이션 라이트 밤', '0', '2', '62.48', '22.45');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '피치씨드 하이드레이션 에멀젼', '0', '1', '32.66', '23.09');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '피치씨드 하이드레이션 익스트림 밤', '0', '1', '25', '25.04');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '피치씨드 하이드레이션 토너', '0', '4', '30.5', '38.49');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '와이어리스', '피치씨드 하이드레이션 팩', '0', '2', '61.53', '20.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '레쥬비네이션 롤링 에멀젼', '6', '2', '46.1', '28.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '레쥬비네이션 밤', '6', '1', '19.75', '9.7');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '레쥬비네이션 세럼', '6', '2', '42.4', '26.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '레쥬비네이션 스킨 팩', '6', '3', '45.9', '30.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '레쥬비네이션 에센스', '6', '1', '27.66', '18.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '레쥬비네이션 크림', '6', '4', '20.45', '34.61');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '마유 에센스', '7', '1', '12', '21.46');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '마유 크림', '7', '1', '10.5', '16.75');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '마유 토너패드', '7', '4', '26.78', '38.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '블랙 캐비어 워터 로션', '0', '2', '56.77', '18.38');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '블랙 캐비어 워터 에센스', '0', '1', '32.15', '21.75');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '블랙 캐비어 워터 오일', '0', '4', '21.65', '36.11');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '블랙 캐비어 워터 크림', '0', '2', '53.48', '16.08');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '블랙 캐비어 워터 토너', '0', '3', '52', '43.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 미백 세럼', '0', '2', '61.65', '24.04');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 미백 수분크림', '0', '2', '58.87', '29.54');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 미백 에센스패드', '0', '2', '44.38', '20.87');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 미백 오일크림', '0', '2', '46.68', '25.7');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 미백 토너패드', '0', '2', '52.05', '24.84');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 활성 세럼', '6', '1', '32.59', '29.87');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 활성 수분크림', '6', '1', '25.09', '28.45');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 활성 에센스패드', '6', '1', '22.47', '27.58');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 활성 오일크림', '6', '1', '31.19', '26.27');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '인티오', '어리연 활성 토너패드', '6', '1', '28.3', '21.53');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 리프팅팩', '6', '1', '16.78', '30.44');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 브라이트닝팩', '6', '1', '12.62', '26.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 세럼', '6', '1', '12.81', '20.08');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 수분팩', '6', '1', '17.01', '31.92');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 스틱밤', '6', '1', '10.68', '30.69');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 에센스', '6', '1', '15.32', '19.95');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 쫀득팩', '6', '1', '14.48', '28.64');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생 콜라겐팩', '6', '1', '12.49', '21.3');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생크림', '6', '1', '15.45', '23.65');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '아토아토 재생패드', '6', '1', '16.72', '21.17');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '코라세 아토피 재생 로션', '6', '4', '33.45', '42.19');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '코라세 아토피 재생 스킨', '6', '3', '46.8', '46.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '코라세', '코파세 아토피 재생 밤', '6', '1', '21.55', '21.18');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핌플', '핌플 고쿠 로션 밀크', '0', '4', '28.15', '34.55');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핌플', '핌플 고쿠 모이스쳐 오일', '0', '1', '31.35', '17.55');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핌플', '핌플 고쿠 미스트', '0', '3', '61.55', '41.84');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핌플', '핌플 로밀스 크림 인 팩', '7', '1', '31.92', '19.46');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핌플', '핌플 하다라보 수분 젤', '0', '2', '50.48', '14.96');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핌플', '핌플 하다라보 스킨 패드', '0', '2', '48.16', '12.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '퍼플 오일링 드라이스킨 에멀젼', '0', '1', '25.73', '15.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '퍼플 오일링 드라이스킨 크림', '0', '1', '25.47', '8.16');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '퍼플 오일링 드라이스킨 팩', '0', '1', '24.86', '13.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '퍼플 화이트닝 비타민 세럼', '0', '3', '36.48', '37.92');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '퍼플 화이트닝 비타민 오일', '0', '3', '62.45', '39.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 모이스쳐라이징 밤 크림', '0', '2', '39.58', '10.46');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 모이스쳐라이징 스틱 에센스', '0', '1', '33.45', '30.48');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 모이스쳐라이징 페이셜 에센스', '0', '1', '28.15', '10.5');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 브라이트닝 비타민 오일', '0', '3', '53.44', '35.05');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 브라이트닝 수분 스틱', '0', '4', '32.48', '32.78');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 브라이트닝 페이셜 에센스', '0', '2', '36.48', '8.15');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 화이트닝 오일 인 밤', '0', '1', '28.88', '9.7');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '핑켓트', '핑크 화이트닝 페이셜 에센스', '0', '3', '47', '33.86');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인로션 미백크림', '7', '4', '32.42', '51.97');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인로션 에센스', '7', '4', '25.53', '35.53');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인로션 크림', '7', '4', '28.75', '41.31');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인스킨 세럼', '7', '4', '26.78', '53.29');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인패드 스킨', '7', '4', '26.13', '41.57');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인패드 재생세럼', '7', '4', '26.48', '39.5');");
        db.execSQL("INSERT INTO PRODUCT VALUES (NULL, '하늘', '나라오 인패드 재생오일', '7', '4', '25.86', '41.32');");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        //버전이 업그레이드 됐을 경우 작업할 내용을 작성합니다.
        db.execSQL("DROP TABLE IF EXISTS PRODUCT");
        onCreate(db);
    }

}